# Generated by Django 4.2 on 2024-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_message_name', models.CharField(help_text='Status Message Name', max_length=40, verbose_name='Name')),
                ('contentame', models.CharField(help_text='What the user should be informed about', max_length=300)),
            ],
            options={
                'verbose_name': 'Status Message',
                'verbose_name_plural': 'Status Messages',
            },
        ),
    ]
