# Generated by Django 4.2 on 2024-01-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='contentame',
            new_name='content',
        ),
    ]
