from apps.workflows.tests.add_workflow_to_role_signal_test import AddWorkflowToRoleSignalTest
from apps.workflows.tests.user_form_content_test import UserFormContentTest
from apps.workflows.tests.workflow_sequence_test import WorkflowSequenceTest
