# Generated by Django 4.2 on 2024-01-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0002_workflowstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWorkflowStep',
            fields=[
                ('workflowstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.workflowstep')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workflows.workflowstep',),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('workflowstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.workflowstep')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workflows.workflowstep',),
        ),
        migrations.CreateModel(
            name='FormWorkflowStep',
            fields=[
                ('workflowstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.workflowstep')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workflows.workflowstep',),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
