# Generated by Django 4.2 on 2024-01-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_actionworkflowstep_approvalworkflowstep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionworkflowstep',
            options={},
        ),
        migrations.AlterModelOptions(
            name='approvalworkflowstep',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formworkflowstep',
            options={},
        ),
    ]
