# Generated by Django 4.2 on 2024-01-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companyprofileset_role'),
        ('workflows', '0004_alter_actionworkflowstep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepAction',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_step_name', models.CharField(help_text='Workflow Step Name', max_length=40, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Action Step',
                'verbose_name_plural': 'Action Steps',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepApproval',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_step_name', models.CharField(help_text='Workflow Step Name', max_length=40, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepForm',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_step_name', models.CharField(help_text='Workflow Step Name', max_length=40, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Form Step',
                'verbose_name_plural': 'Form Steps',
            },
        ),
        migrations.RemoveField(
            model_name='approvalworkflowstep',
            name='workflowstep_ptr',
        ),
        migrations.RemoveField(
            model_name='formworkflowstep',
            name='workflowstep_ptr',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='ActionWorkflowStep',
        ),
        migrations.DeleteModel(
            name='ApprovalWorkflowStep',
        ),
        migrations.DeleteModel(
            name='FormWorkflowStep',
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
