# Generated by Django 4.2 on 2024-01-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companyprofileset_role'),
        ('workflows', '0005_workflowstepaction_workflowstepapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormField',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Internal code - Must be unique', max_length=20, unique=True)),
                ('public_name', models.CharField(help_text='Name shown to the user', max_length=40)),
                ('type', models.CharField(choices=[('ShortText', 'Short Text'), ('Numeric', 'Numeric'), ('LongText', 'Long Text'), ('MultipleSelection', 'Multiple Selection'), ('SingleSelection', 'Single Selection'), ('Date', 'Date'), ('Boolean', 'Boolean')], help_text='Type of the form field', max_length=20)),
                ('choices', models.CharField(blank=True, help_text='Comma-separated values. 250 characters max. Required for Multiple Selection or Single Selection type.', max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'verbose_name': 'User Form Field',
                'verbose_name_plural': 'User Form Fields',
            },
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_form_name', models.CharField(help_text='User Form Name', max_length=40, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('fields', models.ManyToManyField(related_name='user_forms', to='workflows.userformfield')),
            ],
            options={
                'verbose_name': 'User Form',
                'verbose_name_plural': 'User Forms',
            },
        ),
    ]
