# Generated by Django 4.2 on 2024-01-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_userformfield_userform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='fields',
        ),
        migrations.CreateModel(
            name='UserFormFieldSet',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.userform')),
                ('user_form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.userformfield')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userform',
            name='form_fields',
            field=models.ManyToManyField(related_name='user_forms', through='workflows.UserFormFieldSet', to='workflows.userformfield'),
        ),
    ]
