# Generated by Django 4.2 on 2024-01-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companyprofileset_role'),
        ('workflows', '0009_rename_fields_userformcontent_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformcontent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
    ]
