# Generated by Django 4.2 on 2024-01-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companyprofileset_role'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0012_alter_userformcontent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSequence',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, choices=[('Form', 'Form'), ('Approval', 'Approval'), ('Action', 'Action')], max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Sequence',
                'verbose_name_plural': 'Workflow Sequences',
                'ordering': ['order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
    ]
