# Generated by Django 4.2 on 2024-01-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_workflowsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstepaction',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowstepapproval',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowstepform',
            name='workflow',
        ),
    ]
