# Generated by Django 4.2 on 2024-02-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_companydepartment_department_name_and_more'),
        ('workflows', '0016_workflowstepapproval_required_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepapproval',
            name='required_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.companyposition'),
        ),
    ]
