# Generated by Django 4.2 on 2024-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_alter_workflowstepapproval_required_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformcontent',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
