# Generated by Django 4.2 on 2024-02-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_userformcontent_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformcontent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workflowsequence',
            name='company',
        ),
    ]
