# Generated by Django 4.2 on 2024-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_remove_userformcontent_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepaction',
            name='class_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstepaction',
            name='class_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstepaction',
            name='class_path',
            field=models.CharField(default='test', max_length=140),
            preserve_default=False,
        ),
    ]
