# Generated by Django 4.2 on 2024-02-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_workflowstepaction_class_kwargs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowstepaction',
            old_name='class_path',
            new_name='module_path',
        ),
    ]
