# Generated by Django 4.2 on 2024-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_rename_class_path_workflowstepaction_module_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepaction',
            name='class_method',
            field=models.CharField(blank=True, help_text='If blank, code should run in constructor', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstepaction',
            name='module_path',
            field=models.CharField(help_text='Example: apps.workflows.action_classes', max_length=140),
        ),
    ]
