# Generated by Django 4.2 on 2024-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='workflows',
            field=models.ManyToManyField(blank=True, to='workflows.workflow'),
        ),
    ]
