# Generated by Django 4.2 on 2024-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
