# Generated by Django 4.2 on 2024-02-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companyprofileset_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(help_text='Company Name', max_length=40, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Department',
                'verbose_name_plural': 'Company Departments',
            },
        ),
        migrations.AddField(
            model_name='companyprofileset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companydepartment'),
        ),
    ]
