# Generated by Django 4.2 on 2024-02-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_companydepartment_companyprofileset_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydepartment',
            name='department_name',
            field=models.CharField(help_text='Department Name', max_length=40, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_name', models.CharField(help_text='Position Name', max_length=40, verbose_name='Name')),
                ('is_approver', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'verbose_name': 'Company Position',
                'verbose_name_plural': 'Company Positions',
            },
        ),
        migrations.AddField(
            model_name='companyprofileset',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.companyposition'),
        ),
    ]
